### ISSUE TITLE
Allow a theme function to return a Promise

### ISSUE THREAD

**Issue by davidlj95** [davidlj95/resume-cli#1]
Currently if the theme's render function returns a promise, the export operation fails

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    at createHtml (/home/davidlj/Code/git/davidlj95/resume/node_modules/@jsonresume/cli/lib/export-resume/index.js:65:10)
```

The `serve` operation inside the theme works anyway

**Comment by davidlj95** [comment]
Quick fix:

```js
  if(html.then) {
    html.then(htmlString => {
      stream.write(htmlString, function (error) {
        if (error) {
          return callback(error);
        }
        stream.close(callback);
      }); 
    }) 
  } else {
    stream.write(html, function (error) {
      if (error) {
        return callback(error);
      }
      stream.close(callback);
    });
```

Based on:
https://stackoverflow.com/questions/27746304/how-do-i-tell-if-an-object-is-a-promise
